In [2]:
import numpy as np

In [39]:
np.random.seed(0)
a = np.array([(1,2,3),(4,5,6),(1,2,3),(4,5,6),(1,2,3),(4,5,6)])
print a.shape, a[0].shape
res = a.dot(a[0])
print res
res_index = np.argsort(res)
print res_index

from sklearn.preprocessing import normalize
print a
normalize(a)



(6, 3) (3,)
[14 32 14 32 14 32]
[0 2 4 1 3 5]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231,  0.56980288,  0.68376346],
       [ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231,  0.56980288,  0.68376346],
       [ 0.26726124,  0.53452248,  0.80178373],
       [ 0.45584231,  0.56980288,  0.68376346]])