In [10]:
import numpy as np
a = np.array([(1,2,3,4,5),(99,98,97,96,95),])
print np.corrcoef(a)
a = np.array([(1,2,3,4,5),(4,5,6,3,2),])
print np.corrcoef(a)
a = np.array([(1,2,3,4,5),(12,13,14,15,16),])
print np.corrcoef(a)

a = np.array([(1.1,1.9,3.1,3.9,4.9),(1,2,3,4,5),])
print np.corrcoef(a)

a = np.array([(1,2,3,4,5,11,12,13,14,15), (1,2,3,4,5,1,2,3,4,5)])
print np.corrcoef(a)

[[ 1. -1.]
 [-1.  1.]]
[[ 1.  -0.6]
 [-0.6  1. ]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 1.         0.9982684]
 [ 0.9982684  1.       ]]
[[ 1.          0.27216553]
 [ 0.27216553  1.        ]]


In [24]:

class MultiLabelBinarizer(object):
    def __init__(self):
        self._label2_index = {}

    def fit(self, labels):
        for label in labels:
            index = self._label2_index.get(label)
            if index is None:
                self._label2_index[label] = len(self._label2_index)

    def transform(self, values):
        result = np.zeros((1, len(self._label2_index)), dtype='int')
        for value in values:
            index = self._label2_index.get(value)
            if index is None:
                continue
            result[0, index] = 1
        return result


In [25]:
import sklearn.preprocessing as pp
mb = MultiLabelBinarizer()
mb.fit(['bj', 'sh', 'hf'])
print mb.transform(['bj', 'sh', 'sh', '001', '001', '001'])

mb = pp.MultiLabelBinarizer()
mb.fit([['bj', 'sh', 'hf']])
print mb.transform([['bj', 'sh', 'sh']])


[[1 1 0]]
[[1 0 1]]


In [71]:
import numpy as np

a = np.array([
        [11,2,23,4,5],
        [1,2,3,4,5],
        [3,2,4,5,6]], dtype='float32')

def normalize(data):
    norm = np.linalg.norm(data, axis=1)
    for row in range(data.shape[0]):
        data[row,:] = data[row,:] / norm[row]
    return data

a = normalize(a)
sim = np.dot(a, a.T)
print sim
sim = np.sum(sim, axis=0)-1
print sim
             
             

[[ 1.          0.63934648  0.7157138 ]
 [ 0.63934648  1.00000012  0.98072332]
 [ 0.7157138   0.98072332  1.        ]]
[ 1.35506034  1.62006998  1.69643712]


In [87]:
from collections import Counter
import logging

c = Counter()
max_count = 0
line_counter = 0

total_count = 0
for l in open('beijing_ips'):
    f = l.split(',')
    ip = f[0]
    count = int(f[1])
    total_count += count

    line_counter += 1

print 'count done'

fout = open('beijing_ips2', 'w')
for l in open('beijing_ips'):
    f = l.split(',')
    ip = f[0]
    count = int(f[1])
    ratio = float(count) / total_count  # 使用该ip的用户，在所有北京用户中的占比。
    fout.write('%s\t%s\t%s\n' % (ip, count, ratio))
fout.close()

print 'done'

    

count done
done
