In [32]:
import numpy as np
np.random.seed(0)
a1 = np.ones((2,3))
a2 = np.random.random((2,3))
a1 = a1 + a2
print a1
print a1.ravel()
print a1.reshape((3,2)).sum(axis=1)
print a1.min(axis=1)
print a1.cumsum(axis=1) # cumulative sum

# ufunc = universal functions, operate elementwide on a ndarray
print 'ufunc'
print np.sqrt(a1)
print np.add(a1, a2)
print a1+a2 # translated into np.add(a1,a2)
print np.exp(a1)



[[ 1.5488135   1.71518937  1.60276338]
 [ 1.54488318  1.4236548   1.64589411]]
[ 1.5488135   1.71518937  1.60276338  1.54488318  1.4236548   1.64589411]
[ 3.26400287  3.14764656  3.06954891]
[ 1.5488135  1.4236548]
[[ 1.5488135   3.26400287  4.86676625]
 [ 1.54488318  2.96853798  4.6144321 ]]
ufunc
[[ 1.24451336  1.30965238  1.26600291]
 [ 1.2429333   1.19317006  1.28292405]]
[[ 2.09762701  2.43037873  2.20552675]
 [ 2.08976637  1.8473096   2.29178823]]
[[ 2.09762701  2.43037873  2.20552675]
 [ 2.08976637  1.8473096   2.29178823]]
[[ 4.70588336  5.55772786  4.96673844]
 [ 4.68742402  4.15226845  5.18564439]]


In [45]:
# indexing
a1 = np.ones((5,5))
print a1
a1[::2,::2] = 8 # 每行所有元素中每隔两个元素，每列也是
print a1
print a1 ** 2 # 计算平方

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 8.  1.  8.  1.  8.]
 [ 1.  1.  1.  1.  1.]
 [ 8.  1.  8.  1.  8.]
 [ 1.  1.  1.  1.  1.]
 [ 8.  1.  8.  1.  8.]]
[[ 64.   1.  64.   1.  64.]
 [  1.   1.   1.   1.   1.]
 [ 64.   1.  64.   1.  64.]
 [  1.   1.   1.   1.   1.]
 [ 64.   1.  64.   1.  64.]]


In [77]:
# Multidimensional arrays
a1 = np.fromfunction(lambda x, y: x + y, (4,5), dtype=int)
print a1
print a1[0:3,1]
print a1[2,:] 
print a1[2] # same as a1[2,:]
print a1[2,...] # same as a1[2,:]

print np.array([x for x in a1.flat])
print a1.ravel()

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
[1 2 3]
[2 3 4 5 6]
[2 3 4 5 6]
[2 3 4 5 6]
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7]
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7]


In [89]:
# shape manipulation
np.random.seed(0)
a1 = np.random.random((3,4))
a1 *= 4
print a1
print np.floor(a1)
print np.ceil(a1)
print a1.reshape((2,6))
print a1.reshape((2,6)).T

[[ 2.19525402  2.86075747  2.4110535   2.17953273]
 [ 1.6946192   2.58357645  1.75034885  3.567092  ]
 [ 3.85465104  1.53376608  3.16690015  2.11557968]]
[[ 2.  2.  2.  2.]
 [ 1.  2.  1.  3.]
 [ 3.  1.  3.  2.]]
[[ 3.  3.  3.  3.]
 [ 2.  3.  2.  4.]
 [ 4.  2.  4.  3.]]
[[ 2.19525402  2.86075747  2.4110535   2.17953273  1.6946192   2.58357645]
 [ 1.75034885  3.567092    3.85465104  1.53376608  3.16690015  2.11557968]]
[[ 2.19525402  1.75034885]
 [ 2.86075747  3.567092  ]
 [ 2.4110535   3.85465104]
 [ 2.17953273  1.53376608]
 [ 1.6946192   3.16690015]
 [ 2.58357645  2.11557968]]


In [99]:
a1 = np.ones((2,2))
print a1
a1.resize((3,3)) # modify the underlying array, fill with zero
print a1
a2 = np.ones((2,3)) * 2
print a2
print np.vstack((a1, a2))
a2 = np.ones((3,4)) * 2
print a2
print np.hstack((a1,a2))


[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 1.  1.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
[[ 1.  1.  1.  2.  2.  2.  2.]
 [ 1.  0.  0.  2.  2.  2.  2.]
 [ 0.  0.  0.  2.  2.  2.  2.]]


In [145]:
# shortcuts
print np.r_[1:9, 0,0,0, 3,2,1]
print np.r_['-1,2,0', [1,2,3], [4,5,6]]


[1 2 3 4 5 6 7 8 0 0 0 3 2 1]
[[1 4]
 [2 5]
 [3 6]]


In [158]:
# view & copy
a1 = np.random.random((2,3))
a2 = a1.view()
print a1 is a2
print a2.base is a1 # a2使用a1作为底层存储，所以修改a2会相应的修改a1
a2.shape = 3,2
print a1
print a2

a3 = a1[:,2]
print a3 # 此时a3是a1的一个view

a4 = a1.copy() # deepcopy
print a4


False
True
[[ 0.56660145  0.26538949  0.52324805]
 [ 0.09394051  0.5759465   0.9292962 ]]
[[ 0.56660145  0.26538949]
 [ 0.52324805  0.09394051]
 [ 0.5759465   0.9292962 ]]
[ 0.52324805  0.9292962 ]
[[ 0.56660145  0.26538949  0.52324805]
 [ 0.09394051  0.5759465   0.9292962 ]]
