In [1]:
import numpy as np
np.random.seed(0)
a1 = np.ones((2,3))
a2 = np.random.random((2,3))
a1 = a1 + a2
print a1
print a1.ravel()
print a1.reshape((3,2)).sum(axis=1)
print a1.min(axis=1)
print a1.cumsum(axis=1) # cumulative sum

# a1.dot(a1.T)  # 矩阵乘法，内积
# a1 * a1.T  # 外积
# np.linalg.norm( a1 )  # 范数
# axis=0 按列处理； axis=1 按行处理；

# ufunc = universal functions, operate elementwide on a ndarray
print 'ufunc'
print np.sqrt(a1)
print np.add(a1, a2)
print a1+a2 # translated into np.add(a1,a2)
print np.exp(a1)



[[ 1.5488135   1.71518937  1.60276338]
 [ 1.54488318  1.4236548   1.64589411]]
[ 1.5488135   1.71518937  1.60276338  1.54488318  1.4236548   1.64589411]
[ 3.26400287  3.14764656  3.06954891]
[ 1.5488135  1.4236548]
[[ 1.5488135   3.26400287  4.86676625]
 [ 1.54488318  2.96853798  4.6144321 ]]
[[ 7.90954827  7.47255231]
 [ 7.47255231  7.12242447]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [45]:
# indexing
a1 = np.ones((5,5))
print a1
a1[::2,::2] = 8 # 每行所有元素中每隔两个元素，每列也是
print a1
print a1 ** 2 # 计算平方

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 8.  1.  8.  1.  8.]
 [ 1.  1.  1.  1.  1.]
 [ 8.  1.  8.  1.  8.]
 [ 1.  1.  1.  1.  1.]
 [ 8.  1.  8.  1.  8.]]
[[ 64.   1.  64.   1.  64.]
 [  1.   1.   1.   1.   1.]
 [ 64.   1.  64.   1.  64.]
 [  1.   1.   1.   1.   1.]
 [ 64.   1.  64.   1.  64.]]


In [77]:
# Multidimensional arrays
a1 = np.fromfunction(lambda x, y: x + y, (4,5), dtype=int)
print a1
print a1[0:3,1]
print a1[2,:] 
print a1[2] # same as a1[2,:]
print a1[2,...] # same as a1[2,:]

print np.array([x for x in a1.flat])
print a1.ravel()

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
[1 2 3]
[2 3 4 5 6]
[2 3 4 5 6]
[2 3 4 5 6]
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7]
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7]


In [89]:
# shape manipulation
np.random.seed(0)
a1 = np.random.random((3,4))
a1 *= 4
print a1
print np.floor(a1)
print np.ceil(a1)
print a1.reshape((2,6))
print a1.reshape((2,6)).T

[[ 2.19525402  2.86075747  2.4110535   2.17953273]
 [ 1.6946192   2.58357645  1.75034885  3.567092  ]
 [ 3.85465104  1.53376608  3.16690015  2.11557968]]
[[ 2.  2.  2.  2.]
 [ 1.  2.  1.  3.]
 [ 3.  1.  3.  2.]]
[[ 3.  3.  3.  3.]
 [ 2.  3.  2.  4.]
 [ 4.  2.  4.  3.]]
[[ 2.19525402  2.86075747  2.4110535   2.17953273  1.6946192   2.58357645]
 [ 1.75034885  3.567092    3.85465104  1.53376608  3.16690015  2.11557968]]
[[ 2.19525402  1.75034885]
 [ 2.86075747  3.567092  ]
 [ 2.4110535   3.85465104]
 [ 2.17953273  1.53376608]
 [ 1.6946192   3.16690015]
 [ 2.58357645  2.11557968]]


In [99]:
a1 = np.ones((2,2))
print a1
a1.resize((3,3)) # modify the underlying array, fill with zero
print a1
a2 = np.ones((2,3)) * 2
print a2
print np.vstack((a1, a2))
a2 = np.ones((3,4)) * 2
print a2
print np.hstack((a1,a2))


[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 1.  1.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
[[ 1.  1.  1.  2.  2.  2.  2.]
 [ 1.  0.  0.  2.  2.  2.  2.]
 [ 0.  0.  0.  2.  2.  2.  2.]]


In [145]:
# shortcuts
print np.r_[1:9, 0,0,0, 3,2,1]
print np.r_['-1,2,0', [1,2,3], [4,5,6]]


[1 2 3 4 5 6 7 8 0 0 0 3 2 1]
[[1 4]
 [2 5]
 [3 6]]


In [158]:
# view & copy
a1 = np.random.random((2,3))
a2 = a1.view()
print a1 is a2
print a2.base is a1 # a2使用a1作为底层存储，所以修改a2会相应的修改a1
a2.shape = 3,2
print a1
print a2

a3 = a1[:,2]
print a3 # 此时a3是a1的一个view

a4 = a1.copy() # deepcopy
print a4


False
True
[[ 0.56660145  0.26538949  0.52324805]
 [ 0.09394051  0.5759465   0.9292962 ]]
[[ 0.56660145  0.26538949]
 [ 0.52324805  0.09394051]
 [ 0.5759465   0.9292962 ]]
[ 0.52324805  0.9292962 ]
[[ 0.56660145  0.26538949  0.52324805]
 [ 0.09394051  0.5759465   0.9292962 ]]


In [26]:
import numpy as np

a = np.arange(5) ** 2
print a
i = [1,2,3,2,1]
print a[i]

np.random.seed(0)
a = np.random.random((3,3))
print 'a', a
i = [[0,1,1],
     [1,0,2]]
print a[i]
print a[[0,1,0,1]] # 指定需要哪些行
i = np.array([[True,False,False], # 使用和目标array相同shape的bool array，直接指定需要哪些数值
           [False,False,True]], dtype=bool)
print 'boolean', a[i]


[ 0  1  4  9 16]
[1 4 9 4 1]
a [[ 0.5488135   0.71518937  0.60276338]
 [ 0.54488318  0.4236548   0.64589411]
 [ 0.43758721  0.891773    0.96366276]]
[ 0.71518937  0.54488318  0.64589411]
[[ 0.5488135   0.71518937  0.60276338]
 [ 0.54488318  0.4236548   0.64589411]
 [ 0.5488135   0.71518937  0.60276338]
 [ 0.54488318  0.4236548   0.64589411]]
boolean [ 0.5488135   0.64589411]
(12, 2)


/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2


In [33]:
import numpy as np

a = np.arange(24)
a.shape = 6,-1 # whatever the column count is
print a
print a[np.array([True,False,False,True,True,False]), :] # 注意，这里需要转换成 np.array 进行 index

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [12 13 14 15]
 [16 17 18 19]]


In [101]:
# linalg: linear algebra
import numpy as np

np.random.seed(1)
A = np.floor(np.random.random((3,3)) * 10)
print A
print np.diag(A) # 对角元素列表
print 'equal', np.trace(A), np.diag(A).sum() # 对角元素和

b = np.array((8,4,1))
ans = np.linalg.solve(A, b)
print 'Ax=b', ans

# 求解方程组的解
print 'solve loss', abs(np.sum(np.dot(A, ans) - b))

# 逆矩阵
print 'inv loss', abs(np.sum(np.dot(np.linalg.inv(A), A) - np.eye(3)))

# 特征 eigen
print 'eig', np.linalg.eig(A) 

# 行列式（是一个值）
print 'det', np.linalg.det(A)

# 求解伴随矩阵
print 'A*', np.linalg.det(A) * np.linalg.inv(A)

# 矩阵的秩rank
print 'rank A', np.linalg.matrix_rank(A)
print 'rank Ab', np.linalg.matrix_rank(np.hstack((A, b.reshape((3,1)))))
print '因为rank(A)==rank(Ab)，所以Ax=b有唯一解，Ab可以由A线性表示'

A = np.eye(3)
print 'det', np.linalg.det(A)


[[ 4.  7.  0.]
 [ 3.  1.  0.]
 [ 1.  3.  3.]]
[ 4.  1.  3.]
equal 8.0 8.0
Ax=b [ 1.17647059  0.47058824 -0.52941176]
solve loss 4.4408920985e-16
inv loss 1.11022302463e-16
eig (array([ 3.        , -2.32182538,  7.32182538]), array([[ 0.        ,  0.72191546, -0.80590655],
       [ 0.        , -0.65197479, -0.38244012],
       [ 1.        ,  0.231877  , -0.45194489]]))
det -51.0
A* [[  3. -21.  -0.]
 [ -9.  12.   0.]
 [  8.  -5. -17.]]
rank A 3
rank Ab 3
因为rank(A)==rank(Ab)，所以Ax=b有唯一解，Ab可以由A线性表示
det 1.0


In [11]:
# 线性代数

import numpy as np

# 特征（特征值和特征向量）eigenvalue
A = np.diag((1,2,3))
eigenvalue, eigenvector = np.linalg.eig(A)
print 'eign value:', eigenvalue
print 'eign vector:\n', eigenvector

eigenvector *= 4
print 'left value:', np.dot(A, eigenvector)
print 'right value:', eigenvalue * eigenvector

# 正交矩阵
def is_diagonal_matrix(A):
    return (A.T == np.linalg.inv(A)).all() # 全部都是True
print 'is diagonal matrix:', is_diagonal_matrix(A)
print 'is diagonal matrix:', is_diagonal_matrix(np.eye(2))


eign value: [ 1.  2.  3.]
eign vector:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
left value: [[  4.   0.   0.]
 [  0.   8.   0.]
 [  0.   0.  12.]]
right value: [[  4.   0.   0.]
 [  0.   8.   0.]
 [  0.   0.  12.]]
is diagonal matrix: False
is diagonal matrix: True


In [112]:
# 数理统计
import numpy as np

A = np.diag((1,2,3))
print 'cov', np.cov(A) # 协方差

A = np.array((1,2,3))
print 'var', np.var(A) # 方差

print 'mean', np.mean(A) # 均值




cov [[ 0.33333333 -0.33333333 -0.5       ]
 [-0.33333333  1.33333333 -1.        ]
 [-0.5        -1.          3.        ]]
var 0.666666666667
mean 2.0


In [18]:
fibonacci_progression_matrix = np.array([[1, 1], [1, 0]])
vec = np.array([[1, 1]]).T
for i in range(4):
    vec = np.dot(fibonacci_progression_matrix, vec)
    print vec
    

[[2]
 [1]]
[[3]
 [2]]
[[5]
 [3]]
[[8]
 [5]]
