In [5]:
from sklearn import *
import matplotlib as mp
import matplotlib.pyplot as plt
import numpy as np

import sklearn.preprocessing as pp

In [26]:
binarizer = pp.Binarizer(threshold=0.5)
print binarizer.transform([0.4,0.5,0.6]) # 大于threshold的都变成1，其他都变成0

[[ 0.  0.  1.]]


D:\Program Files\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [38]:
ft = pp.FunctionTransformer(lambda x: x+1)
print ft.fit_transform([[1,2,3],[3,4,5]]) # 对传入的元素每个调用指定的函数

[[2 3 4]
 [4 5 6]]


In [40]:
i = pp.Imputer(missing_values='NaN', strategy='mean') # 补全缺失的值
print i.fit_transform([[1,np.NaN], # 使用每一列的均值进行替换
             [np.NaN,2],
             [3,4]])
i = pp.Imputer(missing_values=99, strategy='mean')
print i.fit_transform([[1,99],
             [99,2],
             [3,4]])


[[ 1.  3.]
 [ 2.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  2.]
 [ 3.  4.]]


In [41]:
# Kernel Centerer TODO

In [46]:
print pp.label_binarize([11, 33, 99, 222, 123], classes=[11, 33, 99, 222]) # 这是一个函数，输入时(目标分类，所有分类的列表)
# 找不到的分类输出为全0

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [57]:
mlb = pp.MultiLabelBinarizer()
print mlb.fit_transform([('good','man','is','me'),('good','boy'),('bad','man'),('bad','boy')]) # 每个分类有若干个标签


[[0 0 1 1 1 1]
 [0 1 1 0 0 0]
 [1 0 0 0 1 0]
 [1 1 0 0 0 0]]


In [59]:
le = pp.LabelEncoder()
print le.fit_transform(['good','bad','nice','very_good','so_so']) # 将类别标签编码为数字

[1 0 2 4 3]


In [85]:
tags = ['good','bad','nice','very_good','so_so']
tag_nums = pp.LabelEncoder().fit_transform(tags) # 将列表标签变为数值
print pp.label_binarize(tag_nums, list(set(tag_nums))) # 将数值二进制化

x = np.array([
        [1,2,3,4],
        [5,3,2,1],
        [9,44,3,3]])
print pp.binarize(x, threshold=2.5) # 将数值二分为 0 或者 1

[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]
[[0 0 1 1]
 [1 1 0 0]
 [1 1 1 1]]


In [68]:
X = [[100,3],
    [200,2],
    [300,1]]
sX = pp.scale(X) # 把每一列的重要性变得一样
print sX
print sX.mean(axis=0), sX.std(axis=0) # scale之后 mean=0 var=1

[[-1.22474487  1.22474487]
 [ 0.          0.        ]
 [ 1.22474487 -1.22474487]]
[ 0.  0.] [ 1.  1.]


In [70]:
min_max_scaler = preprocessing.MinMaxScaler() # 限制每一列的最大最小值。默认将输入列的最小最大值映射到 [0,1]
print min_max_scaler.fit_transform([[2,300],
                                   [1,150],
                                   [0,0]])

[[ 1.   1. ]
 [ 0.5  0.5]
 [ 0.   0. ]]


In [73]:
scaler = preprocessing.MaxAbsScaler() # 限制每一列的最大最小值。默认将输入列的最小最大值映射到 [-1,1]，0还是映射到0.
print scaler.fit_transform([[2,-300],
                           [1,-150],
                           [0,0]])

[[ 1.  -1. ]
 [ 0.5 -0.5]
 [ 0.   0. ]]
