In [34]:
from sklearn import *
import matplotlib as mp
import matplotlib.pyplot as plt
import numpy as np

import sklearn.preprocessing as pp

In [76]:
# 处理标签值

print '二值化'

binarizer = pp.Binarizer(threshold=0.5, copy=False) # copy为False的时候，会直接操作输入的nparray（传入内置list仍然会进行copy）
ori = np.array([0.4,0.5,0.6])
print binarizer.transform(ori) # 大于threshold的都变成1，其他都变成0
print ori

print '标签二进制化'
print pp.label_binarize([11, 33, 99, 222, 123], classes=[11, 33, 99, 222]) # 这是一个函数，输入是： (目标分类，所有分类的列表)
# 找不到的分类输出为全0

print

X = np.array([[11, 111, 'china'], [12, 122, 'japan'], [13, 133, 'russia'], [14, 144, 'china']])
X0 = X[:,0:2]
X1 = pp.label_binarize(X[:,2], classes=['china', 'japan']) # 这是一个函数，输入参数为： (目标分类，所有分类的列表)
print np.hstack((X0, X1))

print '不需要指定标签列表的标签二进制化'

lb = pp.LabelBinarizer()
lb.fit(X[:,2])
print lb.classes_
print lb.transform(X[:,2])

print 'label值重新编号'

le = pp.LabelEncoder() # 将所有label重新进行编号
X = [11,22,33,'label1','label2'] # 重新编号为 0~4
le.fit(X)
print le.transform(X)

print '多值标签的二进制化'

mlb = pp.MultiLabelBinarizer()
X = [('good','man','is','me'),('good','boy'),('bad','man'),('bad','boy')]

mlb.fit(X) # 每个分类有若干个标签
print mlb.classes_
print mlb.transform(X)

print '标签数值化'
le = pp.LabelEncoder()
print le.fit_transform(['good','bad','nice','very_good','so_so']) # 将类别标签编码为数字

print '标签数值化 -> 数值二进制化'
tags = ['good','bad','nice','very_good','so_so']
tag_nums = pp.LabelEncoder().fit_transform(tags) # 将列表标签变为数值
print pp.label_binarize(tag_nums, list(set(tag_nums))) # 将数值二进制化

print '多标签同时处理，变为稀疏矩阵'
# 多列label同时进行二进制化处理
X = [[1,2],
     [4,5],
     [7,2]]
ohe = pp.OneHotEncoder()
ohe.fit(X)
print ohe.transform(X) # 结果是一个稀疏矩阵（三元组表示法）

'''
[1,0,0, 1,0]
[0,1,0, 0,1]
[0,0,1, 1,0]
稀疏矩阵表示法：
(0,0) 1
(0,3) 1
(1,1) 1
(1,4) 1
(2,2) 1
(2,3) 1
'''

二值化
[[ 0.  0.  1.]]
[ 0.  0.  1.]
标签二进制化
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]

[['11' '111' '1' '0']
 ['12' '122' '0' '1']
 ['13' '133' '0' '0']
 ['14' '144' '1' '0']]
不需要指定标签列表的标签二进制化
['china' 'japan' 'russia']
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]
label值重新编号
[0 1 2 3 4]
多值标签的二进制化
['bad' 'boy' 'good' 'is' 'man' 'me']
[[0 0 1 1 1 1]
 [0 1 1 0 0 0]
 [1 0 0 0 1 0]
 [1 1 0 0 0 0]]
标签数值化
[1 0 2 4 3]
标签数值化 -> 数值二进制化
[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]
多标签同时处理
  (0, 3)	1.0
  (0, 0)	1.0
  (1, 4)	1.0
  (1, 1)	1.0
  (2, 3)	1.0
  (2, 2)	1.0


//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


'\n[1,0,0, 1,0]\n[0,1,0, 0,1]\n[0,0,1, 1,0]\n\xe7\xa8\x80\xe7\x96\x8f\xe7\x9f\xa9\xe9\x98\xb5\xe8\xa1\xa8\xe7\xa4\xba\xe6\xb3\x95\xef\xbc\x9a\n(0,0) 1\n(0,3) 1\n(1,1) 1\n(1,4) 1\n(2,2) 1\n(2,3) 1\n'

In [45]:
# 对每个值进行任意的转换

ft = pp.FunctionTransformer(lambda x: x+1)
print ft.fit_transform([[1,2,3],[3,4,5]]) # 对传入的元素每个调用指定的函数

# 二值化

x = np.array([
        [22,22,33,44],
        [55,33,22,11],
        [99,44,33,33]])

print pp.binarize(x[:,1:3], threshold=2.5, copy=False) # 将数值二分为 0 或者 1
print x # 加上copy=False之后，直接修改了原始数据x

[[2 3 4]
 [4 5 6]]
[[1 1]
 [1 1]
 [1 1]]
[[22  1  1 44]
 [55  1  1 11]
 [99  1  1 33]]


In [40]:
# 补全缺失值

i = pp.Imputer(missing_values='NaN', strategy='mean') # 补全缺失的值
print i.fit_transform([[1,np.NaN], # 使用每一列的均值进行替换
             [np.NaN,2],
             [3,4]])
i = pp.Imputer(missing_values=99, strategy='mean')
print i.fit_transform([[1,99],
             [99,2],
             [3,4]])


[[ 1.  3.]
 [ 2.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  2.]
 [ 3.  4.]]


In [41]:
# Kernel Centerer TODO

[[ 1.   1. ]
 [ 0.5  0.5]
 [ 0.   0. ]]


In [84]:
# 归一化

print '标准归一化'

X = [[100,3],
    [200,2],
    [300,1]]
X = np.array(X)
sX = pp.scale(X) # 把每一列的重要性变得一样，scale到 [-1,1] 
print sX
print sX.mean(axis=0), sX.std(axis=0) # scale之后 mean=0 var=1

ss = pp.StandardScaler() # 跟上面的scale函数应该是同一个效果
ss.fit(X)
res = ss.transform(X)
print res.mean(axis=0), res.std(axis=0)


print '归一化向量长度'

n = pp.Normalizer(norm='l2', copy=False) # l2应该是L2范数的意思.就是让每个列向量的长度变成1，方向不变（vector标准化）
n.fit(X)
print n.transform(X)

print '按照最大最小值进行归一化'

min_max_scaler = preprocessing.MinMaxScaler() # 限制每一列的最大最小值。默认将输入列的最小最大值映射到 [0,1]
print min_max_scaler.fit_transform([[2,300],
                                   [1,150],
                                   [0,0]])

scaler = preprocessing.MaxAbsScaler() # 限制每一列的最大最小值。默认将输入列的最小最大值映射到 [-1,1]，0还是映射到0.
print scaler.fit_transform([[2,-300],
                           [1,-150],
                           [0,0]])

print '能忍受极端值的归一化（鲁棒性较好的归一化），使用四分点?' # TODO
rs = pp.RobustScaler()
x = [[1,2],
    [3,4],
    [9,14],
    [31,41],
    [5,42],
    [13,34],
    [3,14],
    [3,4],
    [9,14],
    [31,41],
    [5,42],
    [13,34],
    [3,14],
    [10011100,-10101100]]
rs.fit(x)
print x
print rs.transform(x)


标准归一化
[[-1.22474487  1.22474487]
 [ 0.          0.        ]
 [ 1.22474487 -1.22474487]]
[ 0.  0.] [ 1.  1.]
[ 0.  0.] [ 1.  1.]
归一化向量长度
[[ 0.9995503   0.02998651]
 [ 0.99995     0.0099995 ]
 [ 0.99999444  0.00333331]]
按照最大最小值进行归一化
[[ 1.   1. ]
 [ 0.5  0.5]
 [ 0.   0. ]]
[[ 1.  -1. ]
 [ 0.5 -0.5]
 [ 0.   0. ]]
能忍受极端值的归一化（鲁棒性较好的归一化），使用四分点?
[[1, 2], [3, 4], [9, 14], [31, 41], [5, 42], [13, 34], [3, 14], [3, 4], [9, 14], [31, 41], [5, 42], [13, 34], [3, 14], [10011100, -10101100]]
[[ -6.00000000e-01  -3.66412214e-01]
 [ -4.00000000e-01  -3.05343511e-01]
 [  2.00000000e-01   0.00000000e+00]
 [  2.40000000e+00   8.24427481e-01]
 [ -2.00000000e-01   8.54961832e-01]
 [  6.00000000e-01   6.10687023e-01]
 [ -4.00000000e-01   0.00000000e+00]
 [ -4.00000000e-01  -3.05343511e-01]
 [  2.00000000e-01   0.00000000e+00]
 [  2.40000000e+00   8.24427481e-01]
 [ -2.00000000e-01   8.54961832e-01]
 [  6.00000000e-01   6.10687023e-01]
 [ -4.00000000e-01   0.00000000e+00]
 [  1.00110930e+06  -3.08430962e+05]]

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the normalize function.
  warnings.warn(msg, DataConversionWarning)


In [68]:
# 二项式展开？

X = np.array([[1,2],[3,4]])
pf = pp.PolynomialFeatures()
pf.fit(X)
print pf.transform(X)

def test(X): # 进行将每一行进行了二项式展开？
    res = []
    for x in X:
        res.append([1, x[0], x[1], x[0]**2, x[0]*x[1], x[1]**2])
    return np.array(res, dtype='float64')
print test(X)


[[  1.   1.   2.   1.   2.   4.]
 [  1.   3.   4.   9.  12.  16.]]
[[  1.   1.   2.   1.   2.   4.]
 [  1.   3.   4.   9.  12.  16.]]


In [87]:
# 在最左边添加一列1，实际上并没有什么卵用

X = [[11,22],[33,44]]
print pp.add_dummy_feature(X)


[[  1.  11.  22.]
 [  1.  33.  44.]]
