In [2]:
import numpy as np
import numpy.linalg as ll

In [30]:
# 验证 |kAn| = k^n |An|
a = np.array( [[2,1,0],[1,1,3],[4,2,2]] )
k = 3
print(ll.det(a) * k**a.shape[0])
print(ll.det(k * a))


[[1 0]
 [1 3]]
54.0
54.0


In [27]:
# 求解伴随矩阵 A* = |A| A^(-1)
a = np.array( [[2,1,0],[1,1,3],[4,2,2]] )
def adjoint_matrix(mat):
    return ll.det(mat) * ll.inv(mat)
print(adjoint_matrix(a))

[[ -4.  -2.   3.]
 [ 10.   4.  -6.]
 [ -2.  -0.   1.]]


In [41]:

a = np.array( [[2,1,0],[1,1,3],[4,2,2]] )
e12 = np.array([[0,1,0],[1,0,0],[0,0,1]]) # 调换1、2两行的初等变换
print(np.dot(e12, a)) # 对应元素相乘
print(a)
print(np.dot(a, e12)) # 对应元素相乘


[[1 1 3]
 [2 1 0]
 [4 2 2]]
[[2 1 0]
 [1 1 3]
 [4 2 2]]
[[1 2 0]
 [1 1 3]
 [2 4 2]]
